Attempt to fix intermittent test failures
The following two tests fail on occasion:

-- ConcurrentTests.testJar

Error	java.io.FileNotFoundException: /private/var/folders/lb/jb13lc3d4p14rddds27mpmw80000gn/T/BootstrapTest.distDir1578476398972088595/repo/org/eclipse/ceylon/common/1.3.4-SNAPSHOT/org.eclipse.ceylon.common-1.3.4-SNAPSHOT.jar (No such file or directory)

java.lang.RuntimeException: java.io.FileNotFoundException: /private/var/folders/lb/jb13lc3d4p14rddds27mpmw80000gn/T/BootstrapTest.distDir1578476398972088595/repo/org/eclipse/ceylon/common/1.3.4-SNAPSHOT/org.eclipse.ceylon.common-1.3.4-SNAPSHOT.jar (No such file or directory)
at org.eclipse.ceylon.tools.fatjar.CeylonFatJarTool$1.visit(CeylonFatJarTool.java:219)
at org.eclipse.ceylon.cmr.ceylon.loader.ModuleGraph.visit(ModuleGraph.java:196)
at org.eclipse.ceylon.cmr.ceylon.loader.ModuleGraph.visit(ModuleGraph.java:197)
at org.eclipse.ceylon.cmr.ceylon.loader.ModuleGraph.visit(ModuleGraph.java:197)
at org.eclipse.ceylon.cmr.ceylon.loader.ModuleGraph.visit(ModuleGraph.java:189)
at org.eclipse.ceylon.tools.moduleloading.ToolModuleLoader$ToolModuleLoaderContext.visitModules(ToolModuleLoader.java:102)
at org.eclipse.ceylon.tools.moduleloading.ToolModuleLoader.visitModules(ToolModuleLoader.java:162)
at org.eclipse.ceylon.tools.fatjar.CeylonFatJarTool.run(CeylonFatJarTool.java:176)
at org.eclipse.ceylon.tools.test.FatJarToolTests.testJar(FatJarToolTests.java:66)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /private/var/folders/lb/jb13lc3d4p14rddds27mpmw80000gn/T/BootstrapTest.distDir1578476398972088595/repo/org/eclipse/ceylon/common/1.3.4-SNAPSHOT/org.eclipse.ceylon.common-1.3.4-SNAPSHOT.jar (No such file or directory)
at java.util.zip.ZipFile.open(Native Method)
at java.util.zip.ZipFile.<init>(ZipFile.java:225)
at java.util.zip.ZipFile.<init>(ZipFile.java:155)
at java.util.zip.ZipFile.<init>(ZipFile.java:169)
at org.eclipse.ceylon.tools.fatjar.CeylonFatJarTool$1.visit(CeylonFatJarTool.java:190)

-- ConcurrentTests.testResources

Error	/private/var/folders/lb/jb13lc3d4p14rddds27mpmw80000gn/T/BootstrapTest.distDir4664869255889090501/repo/ceylon/language/1.3.4-SNAPSHOT/ceylon.language-1.3.4-SNAPSHOT.car (No such file or directory)

java.io.FileNotFoundException: /private/var/folders/lb/jb13lc3d4p14rddds27mpmw80000gn/T/BootstrapTest.distDir4664869255889090501/repo/ceylon/language/1.3.4-SNAPSHOT/ceylon.language-1.3.4-SNAPSHOT.car (No such file or directory)
at java.util.zip.ZipFile.open(Native Method)
at java.util.zip.ZipFile.<init>(ZipFile.java:225)
at java.util.zip.ZipFile.<init>(ZipFile.java:155)
at java.util.zip.ZipFile.<init>(ZipFile.java:169)
at org.eclipse.ceylon.model.loader.JvmBackendUtil.listPackages(JvmBackendUtil.java:427)
at org.eclipse.ceylon.model.loader.JvmBackendUtil.listPackages(JvmBackendUtil.java:540)
at org.eclipse.ceylon.model.loader.JvmBackendUtil.writeStaticMetamodel(JvmBackendUtil.java:532)
at org.eclipse.ceylon.model.loader.JvmBackendUtil.writeStaticMetamodel(JvmBackendUtil.java:512)
at org.eclipse.ceylon.model.loader.JvmBackendUtil.writeStaticMetamodel(JvmBackendUtil.java:498)
at org.eclipse.ceylon.tools.fatjar.CeylonFatJarTool.run(CeylonFatJarTool.java:224)
at org.eclipse.ceylon.tools.test.FatJarToolTests.testResources(FatJarToolTests.java:134)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)